Imports System.Configuration
Imports System.Configuration.ConfigurationManager
Imports DevExpress.XtraReports.UI

Public Class ReportPreview
    Property Key As KeyReport
    Property NoTransaksi As String
    Property TglAwal As Date
    Property TglAkhir As Date
    Property Gudang As String
    Property KodeItem As String
    Property GrupItem As String
    Property Keterangan As String
    Property Filter As String
    Protected Friend Report As New XtraReport
    Property MultiNo As New List(Of String)

    Enum KeyReport
        Purchase_Order = 1
        Nota_SJ = 4
        DO_Kontan = 5
        DO_Titipan = 6
        Bon_Pesanan_Order = 7
        Bon_Pesanan_Titipan = 8
        Surat_Jalan = 9
        Stuffing = 10
        Surat_Jalan_Super = 11
        TTB = 12
        Retur_Pembelian = 13
        Retur_Penjualan = 14
        Transfer_Barang_Retur = 15
        Nota_Claim = 16
        Surat_Transfer_Barang_Antar_Gudang = 17
        Stok_Awal_Barang = 18
        Retur_Pembelian_Tanpa_TTB = 19
        Adjusment_Stok = 20
        Penerimaan_Transfer_Barang_Retur = 21
        Bukti_Pengembalian_DO_Kontan = 22
        Bukti_Kekurangan_DO_Kontan = 23
    End Enum

    'Private Sub SetConn()
    '    Try
    '        Dim astring = TxtServer.Split(";".ToCharArray(), StringSplitOptions.RemoveEmptyEntries)
    '        Dim config As System.Configuration.Configuration = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None)
    '        config.ConnectionStrings.ConnectionStrings().Item(Me.ProductName & ".My.MySettings.MyConnectionString").ConnectionString = "Data Source=" & astring(0) & ";Initial Catalog=" & Mid(astring(1), 1, Len(astring(1)) - 2) & ";Persist Security Info=True;User ID=sa;Password=Gsmart16816899"
    '        config.Save(ConfigurationSaveMode.Modified)
    '    Catch ex As Exception
    '        MsgBox(Err.Description)
    '    End Try
    'End Sub

    Private Sub ReportPreview_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        Me.Activate()
        Application.DoEvents()
        'SetConn()

        Select Case Key
            'Example Method
            '------------------------------------------------
            'Case KeyReport.Nota
            'Dim MyReport = New XRLaporanBahan
            'MyReport.LblTgl.Text = Keterangan
            'Report = MyReport
            'Report.DataSource = con.execute("SELECT FIELD FROM TABLE")
            Case KeyReport.Bukti_Pengembalian_DO_Kontan
                Using dtcek = SelectCon.execute("select count(NO_PENGEMBALIAN)cnt,NO_PENGEMBALIAN from AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN_DETAIL where ID_TRANSAKSI = '" & NoTransaksi & "' group by NO_PENGEMBALIAN")
                    If dtcek.Rows.Count > 0 Then
                        If dtcek.Rows(0)(0) > 6 Then
                            Dim MyReport = New CetakanBuktiPengembalianCustomer_Menyamping
                            Report = MyReport
                            Report.DataSource = SelectCon.execute("select distinct A.ID_DO_KONTAN,A.TGL,A.ID_TRANSAKSI,A.JUMLAH_BELUM_DIBAYAR,a.TOTAL_PENJUALAN,a.KODE_APPROVE,a.KODE_CUSTOMER,a.NO_DO_KONTAN,a.NO_PENGEMBALIAN,b.NAMA NAMA_CUSTOMER,c.KETERANGAN,iif(C.KETERANGAN = 'Penjualan (-)',sum(c.NILAI) over (partition by C.ID_TRANSAKSI),0) NILAI,iif(C.KETERANGAN = 'Penjualan (-)',(SELECT  right(US.NO_NOTA,5) + ',' 
    FROM AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN_DETAIL US
    WHERE US.ID_TRANSAKSI = A.ID_TRANSAKSI and US.NO_NOTA <> '' and US.NO_NOTA is not null
    FOR XML PATH('')),'') NO_NOTA, c.TOTAL,e.NAMA NAMA_DIVISI,(select count(NO_PENGEMBALIAN)cnt from AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN_DETAIL where ID_TRANSAKSI = A.ID_TRANSAKSI and KETERANGAN= 'Penjualan (-)' group by NO_PENGEMBALIAN) count_nota from AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN A join CUSTOMER b on a.KODE_APPROVE = b.KODE_APPROVE and a.KODE_CUSTOMER = b.ID join AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN_DETAIL c on a.ID_TRANSAKSI = c.ID_TRANSAKSI join DELIVERY_ORDER d on d.ID_TRANSAKSI = a.ID_DO_KONTAN join divisi e on e.KODE = d.DIVISI where A.ID_TRANSAKSI = '" & NoTransaksi & "'")

                        ElseIf dtcek.Rows(0)(0) <= 6 Then
                            Dim MyReport = New CetakanBuktiPengembalianCustomer
                            Report = MyReport
                            Report.DataSource = SelectCon.execute("select A.ID_DO_KONTAN,A.TGL,A.ID_TRANSAKSI,A.JUMLAH_BELUM_DIBAYAR,a.TOTAL_PENJUALAN,a.KODE_APPROVE,a.KODE_CUSTOMER,a.NO_DO_KONTAN,a.NO_PENGEMBALIAN,b.NAMA NAMA_CUSTOMER,c.KETERANGAN,c.NILAI,c.NO_NOTA,c.TANGGAL_NOTA,c.TOTAL,e.NAMA NAMA_DIVISI from AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN A join CUSTOMER b on a.KODE_APPROVE = b.KODE_APPROVE and a.KODE_CUSTOMER = b.ID join AR_BUKTI_PENGEMBALIAN_UANG_DO_KONTAN_DETAIL c on a.ID_TRANSAKSI = c.ID_TRANSAKSI join DELIVERY_ORDER d on d.ID_TRANSAKSI = a.ID_DO_KONTAN join divisi e on e.KODE = d.DIVISI where A.ID_TRANSAKSI = '" & NoTransaksi & "'")
                        End If
                    End If
                End Using
            Case KeyReport.Bukti_Kekurangan_DO_Kontan
                Using dtcek = SelectCon.execute("select count(NO_KEKURANGAN)cnt,NO_KEKURANGAN from AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN_DETAIL where ID_TRANSAKSI = '" & NoTransaksi & "' group by NO_KEKURANGAN")
                    If dtcek.Rows.Count > 0 Then
                        If dtcek.Rows(0)(0) > 6 Then
                            Dim MyReport = New CetakanBuktiKekuranganCustomer_Menyamping
                            Report = MyReport
                            Report.DataSource = SelectCon.execute("select distinct A.ID_DO_KONTAN,A.TGL,A.ID_TRANSAKSI,A.JUMLAH_KURANG_BAYAR,a.TOTAL_PENJUALAN,a.KODE_APPROVE,a.KODE_CUSTOMER,a.NO_DO_KONTAN,a.NO_KEKURANGAN,b.NAMA NAMA_CUSTOMER,c.KETERANGAN,iif(C.KETERANGAN = 'Penjualan (-)',sum(c.NILAI) over (partition by C.ID_TRANSAKSI),0) NILAI,iif(C.KETERANGAN = 'Penjualan (-)',(SELECT  right(US.NO_NOTA,5) + ',' 
    FROM AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN_DETAIL US
    WHERE US.ID_TRANSAKSI = A.ID_TRANSAKSI and US.NO_NOTA <> '' and US.NO_NOTA is not null
    FOR XML PATH('')),'') NO_NOTA, c.TOTAL,e.NAMA NAMA_DIVISI,(select count(NO_KEKURANGAN)cnt from AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN_DETAIL where ID_TRANSAKSI = A.ID_TRANSAKSI and KETERANGAN= 'Penjualan (-)' group by NO_KEKURANGAN) count_nota from AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN A join CUSTOMER b on a.KODE_APPROVE = b.KODE_APPROVE and a.KODE_CUSTOMER = b.ID join AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN_DETAIL c on a.ID_TRANSAKSI = c.ID_TRANSAKSI join DELIVERY_ORDER d on d.ID_TRANSAKSI = a.ID_DO_KONTAN join divisi e on e.KODE = d.DIVISI where A.ID_TRANSAKSI = '" & NoTransaksi & "'")
                        Else
                            Dim MyReport = New CetakanBuktiKekuranganCustomer
                            Report = MyReport
                            Report.DataSource = SelectCon.execute("select A.ID_DO_KONTAN,A.TGL,A.ID_TRANSAKSI,A.JUMLAH_KURANG_BAYAR,a.TOTAL_PENJUALAN,a.KODE_APPROVE,a.KODE_CUSTOMER,a.NO_DO_KONTAN,a.NO_KEKURANGAN,b.NAMA NAMA_CUSTOMER,c.KETERANGAN,c.NILAI,c.NO_NOTA,c.TANGGAL_NOTA,c.TOTAL,e.NAMA NAMA_DIVISI from AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN A join CUSTOMER b on a.KODE_APPROVE = b.KODE_APPROVE and a.KODE_CUSTOMER = b.ID join AR_BUKTI_KEKURANGAN_UANG_DO_KONTAN_DETAIL c on a.ID_TRANSAKSI = c.ID_TRANSAKSI join DELIVERY_ORDER d on d.ID_TRANSAKSI = a.ID_DO_KONTAN join divisi e on e.KODE = d.DIVISI where A.ID_TRANSAKSI = '" & NoTransaksi & "'")

                        End If
                    End If
                End Using

                'Case KeyReport.Purchase_Order
                '    Report = New XRNotaPO
                '    Report.DataSource = SelectCon.execute("SELECT dbo.PURCHASE_ORDER.ID_TRANSAKSI, dbo.PURCHASE_ORDER.NO_PO, dbo.PURCHASE_ORDER.TGL, dbo.PURCHASE_ORDER.TGL_PENGAKUAN, dbo.PURCHASE_ORDER.DIVISI, dbo.PURCHASE_ORDER.JENIS_PPN, dbo.PURCHASE_ORDER.KODE_CUSTOMER, dbo.PURCHASE_ORDER.KODE_APPROVE, dbo.PURCHASE_ORDER.ALAMAT_KIRIM, dbo.PURCHASE_ORDER.PEMBAYARAN, dbo.PURCHASE_ORDER.TERMS, dbo.PURCHASE_ORDER.JATUH_TEMPO, dbo.PURCHASE_ORDER.KETERANGAN_CETAK, dbo.PURCHASE_ORDER.SUBTOTAL, dbo.PURCHASE_ORDER.DPP, dbo.PURCHASE_ORDER.PPN, dbo.DETAIL_PURCHASE_ORDER.ID_BARANG, dbo.DETAIL_PURCHASE_ORDER.KOLI, dbo.DETAIL_PURCHASE_ORDER.QUANTITY, dbo.DETAIL_PURCHASE_ORDER.SATUAN, dbo.DETAIL_PURCHASE_ORDER.HARGA, dbo.DETAIL_PURCHASE_ORDER.DISC, dbo.DETAIL_PURCHASE_ORDER.DISKON_SATUAN, dbo.DETAIL_PURCHASE_ORDER.URUTAN, dbo.BARANG.KODE, dbo.BARANG.KODE_PABRIK, dbo.BARANG.NAMA AS NAMA_BARANG, dbo.SBU.NAMA AS NAMA_SBU, dbo.CUSTOMER.NAMA AS NAMA_CUSTOMER, dbo.CUSTOMER.ALAMAT_KANTOR, dbo.CUSTOMER.PROPINSI, dbo.CUSTOMER.KOTA, dbo.CUSTOMER.KODE_POS, dbo.CUSTOMER.NO_NPWP, dbo.DETAIL_PURCHASE_ORDER.KONVERSI, dbo.DETAIL_PURCHASE_ORDER.PCS, dbo.DETAIL_PURCHASE_ORDER.ISI, dbo.PURCHASE_ORDER.KETERANGAN_INTERNAL, dbo.PURCHASE_ORDER.DISC_QTY, dbo.PURCHASE_ORDER.DISC_QTY_NOMINAL, dbo.PURCHASE_ORDER.DISC_REG, dbo.PURCHASE_ORDER.DISC_REG_NOMINAL, dbo.PURCHASE_ORDER.DISC_1, dbo.PURCHASE_ORDER.DISC_1_NOMINAL, dbo.PURCHASE_ORDER.DISC_2, dbo.PURCHASE_ORDER.DISC_2_NOMINAL, dbo.PURCHASE_ORDER.DISC_3, dbo.PURCHASE_ORDER.DISC_3_NOMINAL, dbo.PURCHASE_ORDER.CASH_DISC, dbo.PURCHASE_ORDER.CASH_DISC_NOMINAL, dbo.PURCHASE_ORDER.DISC_QTY1, dbo.PURCHASE_ORDER.DISC_QTY_NOMINAL1, dbo.PURCHASE_ORDER.PERIODE FROM dbo.CUSTOMER RIGHT OUTER JOIN dbo.PURCHASE_ORDER INNER JOIN dbo.DETAIL_PURCHASE_ORDER ON dbo.PURCHASE_ORDER.ID_TRANSAKSI = dbo.DETAIL_PURCHASE_ORDER.ID_TRANSAKSI ON dbo.CUSTOMER.ID = dbo.PURCHASE_ORDER.KODE_CUSTOMER LEFT OUTER JOIN dbo.BARANG ON dbo.DETAIL_PURCHASE_ORDER.ID_BARANG = dbo.BARANG.ID LEFT OUTER JOIN dbo.LINK_SBU_DIVISI LEFT OUTER JOIN dbo.SBU ON dbo.LINK_SBU_DIVISI.KODE_SBU = dbo.SBU.KODE ON dbo.PURCHASE_ORDER.DIVISI = dbo.LINK_SBU_DIVISI.KODE_DIVISI WHERE PURCHASE_ORDER.ID_TRANSAKSI='" & NoTransaksi & "' ORDER BY DETAIL_PURCHASE_ORDER.URUTAN")

                'Case KeyReport.Nota_SJ
                '    Dim PrimaryReport As New XRNotaSJ
                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE "
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "NOTA.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '    Else
                '        filter = "WHERE NOTA.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    PrimaryReport.DataSource = SelectCon.execute("SELECT CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.KOTA, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, DETAIL_NOTA.ID_BARANG, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, DETAIL_NOTA.KOLI, DETAIL_NOTA.QUANTITY, DETAIL_NOTA.SATUAN, DETAIL_NOTA.HARGA, DETAIL_NOTA.DISKON_SATUAN, DETAIL_NOTA.DISC, NOTA.ID_TRANSAKSI, NOTA.NO_NOTA, NOTA.NO_REF, NOTA.TGL, NOTA.TGL_PENGAKUAN, NOTA.ID_STUFFING, NOTA.ID_DO, NOTA.NO_DO, NOTA.TGL_DO, NOTA.DIVISI, NOTA.JENIS_PPN, NOTA.KODE_CUSTOMER, NOTA.KODE_APPROVE, NOTA.CABANG, NOTA.ALAMAT_KIRIM, NOTA.GUDANG, NOTA.SJ_TANPA_HARGA, NOTA.TITIP, NOTA.KETERANGAN_CETAK, NOTA.KETERANGAN_INTERNAL, NOTA.SUBTOTAL, NOTA.DISC_QTY, NOTA.DISC_QTY_NOMINAL, NOTA.DISC_REG, NOTA.DISC_REG_NOMINAL, NOTA.DISC_1, NOTA.DISC_1_NOMINAL, NOTA.DISC_2, NOTA.DISC_2_NOMINAL, NOTA.DISC_3, NOTA.DISC_3_NOMINAL, NOTA.CASH_DISC, NOTA.CASH_DISC_NOMINAL, NOTA.DISC_QTY1, NOTA.DISC_QTY_NOMINAL1, NOTA.DPP, NOTA.PPN, NOTA.PERIODE, NOTA.CRUSER, NOTA.CRTIME, NOTA.MDUSER, NOTA.MDTIME, NOTA.BATAL, NOTA.BAGIAN, NOTA.KODE_EKSPEDISI, NOTA.NO_TRUK, DETAIL_NOTA.KONVERSI, DETAIL_NOTA.PCS, DETAIL_NOTA.URUTAN, NOTA.PENGEMUDI, NOTA.KEPALA_GUDANG, NOTA.CONTROLLER, NOTA.PRINT_PKP, CUSTOMER.NO_NPWP, CUSTOMER.NAMA_PKP, CUSTOMER.ALAMAT_PKP, CUSTOMER.KOTA_NPWP, CUSTOMER.KODE_POS_NPWP FROM BARANG RIGHT OUTER JOIN DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN NOTA INNER JOIN DETAIL_NOTA ON NOTA.ID_TRANSAKSI = DETAIL_NOTA.ID_TRANSAKSI LEFT OUTER JOIN CUSTOMER ON NOTA.KODE_CUSTOMER = CUSTOMER.ID ON DETAIL_CUSTOMER_CABANG.ID = CUSTOMER.ID AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = NOTA.CABANG ON BARANG.ID = DETAIL_NOTA.ID_BARANG " & filter & " AND DETAIL_NOTA.PCS > 0 ORDER BY NOTA.ID_TRANSAKSI ")
                '    'PrimaryReport.DataSource = SelectCon.execute("SELECT CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.KOTA, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, DETAIL_NOTA.ID_BARANG, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, DETAIL_NOTA.KOLI, DETAIL_NOTA.QUANTITY, DETAIL_NOTA.SATUAN, IIF(NOTA.JENIS_PPN='EXCLUDE',DETAIL_NOTA.HARGA/1.1,DETAIL_NOTA.HARGA) 'HARGA', DETAIL_NOTA.DISKON_SATUAN, DETAIL_NOTA.DISC, NOTA.ID_TRANSAKSI, NOTA.NO_NOTA, NOTA.NO_REF, NOTA.TGL, NOTA.TGL_PENGAKUAN, NOTA.ID_STUFFING, NOTA.ID_DO, NOTA.NO_DO, NOTA.TGL_DO, NOTA.DIVISI, NOTA.JENIS_PPN, NOTA.KODE_CUSTOMER, NOTA.KODE_APPROVE, NOTA.CABANG, NOTA.ALAMAT_KIRIM, NOTA.GUDANG, NOTA.SJ_TANPA_HARGA, NOTA.TITIP, NOTA.KETERANGAN_CETAK, NOTA.KETERANGAN_INTERNAL, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.SUBTOTAL/1.1,0),NOTA.SUBTOTAL) 'SUBTOTAL', NOTA.DISC_QTY, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_QTY_NOMINAL/1.1,0),NOTA.DISC_QTY_NOMINAL) 'DISC_QTY_NOMINAL', NOTA.DISC_REG, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_REG_NOMINAL/1.1,0),NOTA.DISC_REG_NOMINAL) 'DISC_REG_NOMINAL', NOTA.DISC_1, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_1_NOMINAL/1.1,0),NOTA.DISC_1_NOMINAL) 'DISC_1_NOMINAL', NOTA.DISC_2, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_2_NOMINAL/1.1,0),NOTA.DISC_2_NOMINAL) 'DISC_2_NOMINAL', NOTA.DISC_3, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_3_NOMINAL/1.1,0),NOTA.DISC_3_NOMINAL) 'DISC_3_NOMINAL', NOTA.CASH_DISC, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.CASH_DISC_NOMINAL/1.1,0),NOTA.CASH_DISC_NOMINAL) 'CASH_DISC_NOMINAL', NOTA.DISC_QTY1, IIF(NOTA.JENIS_PPN='EXCLUDE',ROUND(NOTA.DISC_QTY_NOMINAL1/1.1,0),NOTA.DISC_QTY_NOMINAL1) 'DISC_QTY_NOMINAL1', NOTA.DPP, NOTA.PPN, NOTA.PERIODE, NOTA.CRUSER, NOTA.CRTIME, NOTA.MDUSER, NOTA.MDTIME, NOTA.BATAL, NOTA.BAGIAN, NOTA.KODE_EKSPEDISI, NOTA.NO_TRUK, DETAIL_NOTA.KONVERSI, DETAIL_NOTA.PCS, DETAIL_NOTA.URUTAN, NOTA.PENGEMUDI, NOTA.KEPALA_GUDANG, NOTA.CONTROLLER, NOTA.PRINT_PKP, CUSTOMER.NO_NPWP, CUSTOMER.NAMA_PKP, CUSTOMER.ALAMAT_PKP, CUSTOMER.KOTA_NPWP, CUSTOMER.KODE_POS_NPWP FROM BARANG RIGHT OUTER JOIN DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN NOTA INNER JOIN DETAIL_NOTA ON NOTA.ID_TRANSAKSI = DETAIL_NOTA.ID_TRANSAKSI LEFT OUTER JOIN CUSTOMER ON NOTA.KODE_CUSTOMER = CUSTOMER.ID ON DETAIL_CUSTOMER_CABANG.ID = CUSTOMER.ID AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = NOTA.CABANG ON BARANG.ID = DETAIL_NOTA.ID_BARANG where NOTA.ID_TRANSAKSI='NOTA55822' AND DETAIL_NOTA.PCS > 0 ORDER BY NOTA.ID_TRANSAKSI ")
                '    Report = PrimaryReport

                'Case KeyReport.DO_Kontan
                '    Dim PrimaryReport As New XRNotaDeliveryOrder
                '    PrimaryReport.LabelTitle.Text = "NOTA KONTAN"
                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE "
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "DELIVERY_ORDER.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '    Else
                '        filter = "WHERE DELIVERY_ORDER.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    PrimaryReport.DataSource = SelectCon.execute("SELECT DISTINCT DELIVERY_ORDER.ID_TRANSAKSI, DELIVERY_ORDER.NO_DO, DELIVERY_ORDER.TGL, DELIVERY_ORDER.TGL_PENGAKUAN, DELIVERY_ORDER.TGL_PRICE, DELIVERY_ORDER.DIVISI, DELIVERY_ORDER.JENIS_PPN, DELIVERY_ORDER.KODE_CUSTOMER, DELIVERY_ORDER.KODE_APPROVE, DELIVERY_ORDER.ALAMAT_KIRIM, DELIVERY_ORDER.PEMBAYARAN, DELIVERY_ORDER.TERMS, DELIVERY_ORDER.JATUH_TEMPO, DELIVERY_ORDER.KETERANGAN_CETAK, DELIVERY_ORDER.SUBTOTAL, DELIVERY_ORDER.DPP, DELIVERY_ORDER.PPN, DETAIL_DELIVERY_ORDER.ID_BARANG, DETAIL_DELIVERY_ORDER.KOLI, DETAIL_DELIVERY_ORDER.QUANTITY, DETAIL_DELIVERY_ORDER.SATUAN, DETAIL_DELIVERY_ORDER.HARGA, DETAIL_DELIVERY_ORDER.DISC, DETAIL_DELIVERY_ORDER.DISKON_SATUAN, DETAIL_DELIVERY_ORDER.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, SBU.NAMA AS NAMA_SBU, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.NO_NPWP, DETAIL_DELIVERY_ORDER.KONVERSI, DETAIL_DELIVERY_ORDER.PCS, DETAIL_DELIVERY_ORDER.ISI, DELIVERY_ORDER.ID_PO, DELIVERY_ORDER.CABANG, DELIVERY_ORDER.KETERANGAN_INTERNAL, DELIVERY_ORDER.DISC_QTY, DELIVERY_ORDER.DISC_QTY_NOMINAL, DELIVERY_ORDER.DISC_REG, DELIVERY_ORDER.DISC_REG_NOMINAL, DELIVERY_ORDER.DISC_1, DELIVERY_ORDER.DISC_1_NOMINAL, DELIVERY_ORDER.DISC_2, DELIVERY_ORDER.DISC_2_NOMINAL, DELIVERY_ORDER.DISC_3, DELIVERY_ORDER.DISC_3_NOMINAL, DELIVERY_ORDER.CASH_DISC, DELIVERY_ORDER.CASH_DISC_NOMINAL, DELIVERY_ORDER.DISC_QTY1, DELIVERY_ORDER.DISC_QTY_NOMINAL1, DELIVERY_ORDER.PERIODE, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, USERS.NAMA_USER, CUSTOMER.ALAMAT_PKP, CUSTOMER.NAMA_PKP,PT.NAMA ,DELIVERY_ORDER.PRINT_PKP,LINK_CORPORATION_CUSTOMER.KODE_CORPORATION, SALES.NAMA_USER SALESMAN FROM DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN DELIVERY_ORDER INNER JOIN DETAIL_DELIVERY_ORDER ON DELIVERY_ORDER.ID_TRANSAKSI = DETAIL_DELIVERY_ORDER.ID_TRANSAKSI LEFT OUTER JOIN USERS ON DELIVERY_ORDER.CRUSER = USERS.ID_USER ON DETAIL_CUSTOMER_CABANG.ID = DELIVERY_ORDER.KODE_CUSTOMER AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = DELIVERY_ORDER.CABANG LEFT OUTER JOIN CUSTOMER ON DELIVERY_ORDER.KODE_CUSTOMER = CUSTOMER.ID LEFT JOIN LINK_CORPORATION_CUSTOMER ON LINK_CORPORATION_CUSTOMER.ID_CUSTOMER=CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_DELIVERY_ORDER.ID_BARANG = BARANG.ID LEFT OUTER JOIN LINK_SBU_DIVISI LEFT OUTER JOIN SBU ON LINK_SBU_DIVISI.KODE_SBU = SBU.KODE ON DELIVERY_ORDER.DIVISI = LINK_SBU_DIVISI.KODE_DIVISI LEFT JOIN LINK_PT_SBU ON LINK_SBU_DIVISI.KODE_SBU=LINK_PT_SBU.KODE_SBU LEFT JOIN PT ON LINK_PT_SBU.KODE_PT=PT.KODE LEFT JOIN USERS SALES ON DELIVERY_ORDER.SALES=SALES.ID_USER " & filter)
                '    Report = PrimaryReport

                'Case KeyReport.Bon_Pesanan_Order
                '    Dim PrimaryReport As New XRNotaDeliveryOrder
                '    PrimaryReport.LabelTitle.Text = "BON PESANAN (ORDER)"
                '    PrimaryReport.DataSource = SelectCon.execute("SELECT DISTINCT DELIVERY_ORDER.ID_TRANSAKSI, DELIVERY_ORDER.NO_DO, DELIVERY_ORDER.TGL, DELIVERY_ORDER.TGL_PENGAKUAN, DELIVERY_ORDER.TGL_PRICE, DELIVERY_ORDER.DIVISI, DELIVERY_ORDER.JENIS_PPN, DELIVERY_ORDER.KODE_CUSTOMER, DELIVERY_ORDER.KODE_APPROVE, DELIVERY_ORDER.ALAMAT_KIRIM, DELIVERY_ORDER.PEMBAYARAN, DELIVERY_ORDER.TERMS, DELIVERY_ORDER.JATUH_TEMPO, DELIVERY_ORDER.KETERANGAN_CETAK, DELIVERY_ORDER.SUBTOTAL, DELIVERY_ORDER.DPP, DELIVERY_ORDER.PPN, DETAIL_DELIVERY_ORDER.ID_BARANG, DETAIL_DELIVERY_ORDER.KOLI, DETAIL_DELIVERY_ORDER.QUANTITY, DETAIL_DELIVERY_ORDER.SATUAN, DETAIL_DELIVERY_ORDER.HARGA, DETAIL_DELIVERY_ORDER.DISC, DETAIL_DELIVERY_ORDER.DISKON_SATUAN, DETAIL_DELIVERY_ORDER.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, SBU.NAMA AS NAMA_SBU, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.NO_NPWP, DETAIL_DELIVERY_ORDER.KONVERSI, DETAIL_DELIVERY_ORDER.PCS, DETAIL_DELIVERY_ORDER.ISI, DELIVERY_ORDER.ID_PO, DELIVERY_ORDER.CABANG, DELIVERY_ORDER.KETERANGAN_INTERNAL, DELIVERY_ORDER.DISC_QTY, DELIVERY_ORDER.DISC_QTY_NOMINAL, DELIVERY_ORDER.DISC_REG, DELIVERY_ORDER.DISC_REG_NOMINAL, DELIVERY_ORDER.DISC_1, DELIVERY_ORDER.DISC_1_NOMINAL, DELIVERY_ORDER.DISC_2, DELIVERY_ORDER.DISC_2_NOMINAL, DELIVERY_ORDER.DISC_3, DELIVERY_ORDER.DISC_3_NOMINAL, DELIVERY_ORDER.CASH_DISC, DELIVERY_ORDER.CASH_DISC_NOMINAL, DELIVERY_ORDER.DISC_QTY1, DELIVERY_ORDER.DISC_QTY_NOMINAL1, DELIVERY_ORDER.PERIODE, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, USERS.NAMA_USER, CUSTOMER.ALAMAT_PKP, CUSTOMER.NAMA_PKP, PT.NAMA ,DELIVERY_ORDER.PRINT_PKP,LINK_CORPORATION_CUSTOMER.KODE_CORPORATION, SALES.NAMA_USER SALESMAN FROM DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN DELIVERY_ORDER INNER JOIN DETAIL_DELIVERY_ORDER ON DELIVERY_ORDER.ID_TRANSAKSI = DETAIL_DELIVERY_ORDER.ID_TRANSAKSI LEFT OUTER JOIN USERS ON DELIVERY_ORDER.CRUSER = USERS.ID_USER ON DETAIL_CUSTOMER_CABANG.ID = DELIVERY_ORDER.KODE_CUSTOMER AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = DELIVERY_ORDER.CABANG LEFT OUTER JOIN CUSTOMER ON DELIVERY_ORDER.KODE_CUSTOMER = CUSTOMER.ID LEFT JOIN LINK_CORPORATION_CUSTOMER ON LINK_CORPORATION_CUSTOMER.ID_CUSTOMER=CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_DELIVERY_ORDER.ID_BARANG = BARANG.ID LEFT OUTER JOIN LINK_SBU_DIVISI LEFT OUTER JOIN SBU ON LINK_SBU_DIVISI.KODE_SBU = SBU.KODE ON DELIVERY_ORDER.DIVISI = LINK_SBU_DIVISI.KODE_DIVISI LEFT JOIN LINK_PT_SBU ON LINK_SBU_DIVISI.KODE_SBU=LINK_PT_SBU.KODE_SBU LEFT JOIN PT ON LINK_PT_SBU.KODE_PT=PT.KODE LEFT JOIN USERS SALES ON DELIVERY_ORDER.SALES=SALES.ID_USER WHERE DELIVERY_ORDER.ID_TRANSAKSI='" & NoTransaksi & "'")
                '    Report = PrimaryReport

                'Case KeyReport.DO_Titipan
                '    Dim PrimaryReport As New XRNotaDOTitipan
                '    PrimaryReport.LabelTitle.Text = "NOTA KONTAN"
                '    PrimaryReport.DataSource = SelectCon.execute("	SELECT DISTINCT DELIVERY_ORDER.ID_TRANSAKSI, DELIVERY_ORDER.NO_DO, DELIVERY_ORDER.TGL, DELIVERY_ORDER.TGL_PENGAKUAN, DELIVERY_ORDER.TGL_PRICE, DELIVERY_ORDER.DIVISI, DELIVERY_ORDER.JENIS_PPN, DELIVERY_ORDER.KODE_CUSTOMER, DELIVERY_ORDER.KODE_APPROVE, DELIVERY_ORDER.ALAMAT_KIRIM, 'Kontan Titipan' AS PEMBAYARAN, DELIVERY_ORDER.TERMS, DELIVERY_ORDER.JATUH_TEMPO, DELIVERY_ORDER.KETERANGAN_CETAK, DELIVERY_ORDER.SUBTOTAL, DELIVERY_ORDER.DPP, DELIVERY_ORDER.PPN, DETAIL_DELIVERY_ORDER.ID_BARANG, DETAIL_DELIVERY_ORDER.KOLI, DETAIL_DELIVERY_ORDER.QUANTITY, DETAIL_DELIVERY_ORDER.SATUAN, DELIVERY_ORDER.SUBTOTAL AS HARGA, DETAIL_DELIVERY_ORDER.DISC, 0 AS DISKON_SATUAN, DETAIL_DELIVERY_ORDER.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, 'TITIPAN UANG' AS NAMA_BARANG, SBU.NAMA AS NAMA_SBU, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.NO_NPWP, 1 AS KONVERSI, 1 AS PCS, 1 AS ISI, DELIVERY_ORDER.ID_PO, DELIVERY_ORDER.CABANG, DELIVERY_ORDER.KETERANGAN_INTERNAL, DELIVERY_ORDER.DISC_QTY, DELIVERY_ORDER.DISC_QTY_NOMINAL, DELIVERY_ORDER.DISC_REG, DELIVERY_ORDER.DISC_REG_NOMINAL, DELIVERY_ORDER.DISC_1, DELIVERY_ORDER.DISC_1_NOMINAL, DELIVERY_ORDER.DISC_2, DELIVERY_ORDER.DISC_2_NOMINAL, DELIVERY_ORDER.DISC_3, DELIVERY_ORDER.DISC_3_NOMINAL, DELIVERY_ORDER.CASH_DISC, DELIVERY_ORDER.CASH_DISC_NOMINAL, DELIVERY_ORDER.DISC_QTY1, DELIVERY_ORDER.DISC_QTY_NOMINAL1, DELIVERY_ORDER.PERIODE, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, USERS.NAMA_USER, CUSTOMER.ALAMAT_PKP, CUSTOMER.NAMA_PKP, PT.NAMA ,DELIVERY_ORDER.PRINT_PKP,LINK_CORPORATION_CUSTOMER.KODE_CORPORATION, SALES.NAMA_USER SALESMAN FROM DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN DELIVERY_ORDER LEFT JOIN DETAIL_DELIVERY_ORDER ON DELIVERY_ORDER.ID_TRANSAKSI = DETAIL_DELIVERY_ORDER.ID_TRANSAKSI LEFT OUTER JOIN USERS ON DELIVERY_ORDER.CRUSER = USERS.ID_USER ON DETAIL_CUSTOMER_CABANG.ID = DELIVERY_ORDER.KODE_CUSTOMER AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = DELIVERY_ORDER.CABANG LEFT OUTER JOIN CUSTOMER ON DELIVERY_ORDER.KODE_CUSTOMER = CUSTOMER.ID LEFT JOIN LINK_CORPORATION_CUSTOMER ON LINK_CORPORATION_CUSTOMER.ID_CUSTOMER=CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_DELIVERY_ORDER.ID_BARANG = BARANG.ID LEFT OUTER JOIN LINK_SBU_DIVISI LEFT OUTER JOIN SBU ON LINK_SBU_DIVISI.KODE_SBU = SBU.KODE ON DELIVERY_ORDER.DIVISI = LINK_SBU_DIVISI.KODE_DIVISI LEFT JOIN LINK_PT_SBU ON LINK_SBU_DIVISI.KODE_SBU=LINK_PT_SBU.KODE_SBU LEFT JOIN PT ON LINK_PT_SBU.KODE_PT=PT.KODE LEFT JOIN USERS SALES ON DELIVERY_ORDER.SALES=SALES.ID_USER WHERE DELIVERY_ORDER.ID_TRANSAKSI='" & NoTransaksi & "'")

                '    'Dim SubReport1 As New XrDiskonFormula
                '    'SubReport1.DataMember = Nothing
                '    'SubReport1.DataSource = SelectCon.execute("SELECT ID_TRANSAKSI, NO_TRANSAKSI, DISKON_FORMULA, PERSEN, NOMINAL, URUTAN FROM DETAIL_TRANSAKSI_DISKON WHERE ID_TRANSAKSI='" & NoTransaksi & "'")
                '    'PrimaryReport.XrSubreport1.ReportSource = SubReport1
                '    Report = PrimaryReport

                'Case KeyReport.Bon_Pesanan_Titipan
                '    Dim PrimaryReport As New XRNotaDeliveryOrder
                '    Report = PrimaryReport
                '    PrimaryReport.DataSource = SelectCon.execute("SELECT DISTINCT BON_PESANAN.ID_TRANSAKSI, BON_PESANAN.NO_BON AS NO_DO, BON_PESANAN.TGL, BON_PESANAN.TGL_PENGAKUAN, BON_PESANAN.TGL_PRICE, BON_PESANAN.DIVISI, BON_PESANAN.JENIS_PPN, BON_PESANAN.KODE_CUSTOMER, BON_PESANAN.KODE_APPROVE, BON_PESANAN.ALAMAT_KIRIM, 'Kontan (Titipan)' PEMBAYARAN, 0 TERMS, BON_PESANAN.TGL JATUH_TEMPO, BON_PESANAN.KETERANGAN_CETAK, BON_PESANAN.SUBTOTAL, BON_PESANAN.DPP, BON_PESANAN.PPN, DETAIL_BON_PESANAN.ID_BARANG, DETAIL_BON_PESANAN.KOLI, DETAIL_BON_PESANAN.QUANTITY, DETAIL_BON_PESANAN.SATUAN, DETAIL_BON_PESANAN.HARGA, DETAIL_BON_PESANAN.DISC, DETAIL_BON_PESANAN.DISKON_SATUAN, DETAIL_BON_PESANAN.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, SBU.NAMA AS NAMA_SBU, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.NO_NPWP, DETAIL_BON_PESANAN.KONVERSI, DETAIL_BON_PESANAN.PCS, DETAIL_BON_PESANAN.ISI, '' ID_PO, BON_PESANAN.CABANG, BON_PESANAN.KETERANGAN_INTERNAL, BON_PESANAN.DISC_QTY, BON_PESANAN.DISC_QTY_NOMINAL, BON_PESANAN.DISC_REG, BON_PESANAN.DISC_REG_NOMINAL, BON_PESANAN.DISC_1, BON_PESANAN.DISC_1_NOMINAL, BON_PESANAN.DISC_2, BON_PESANAN.DISC_2_NOMINAL, BON_PESANAN.DISC_3, BON_PESANAN.DISC_3_NOMINAL, BON_PESANAN.CASH_DISC, BON_PESANAN.CASH_DISC_NOMINAL, BON_PESANAN.DISC_QTY1, BON_PESANAN.DISC_QTY_NOMINAL1, BON_PESANAN.PERIODE, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, USERS.NAMA_USER, CUSTOMER.ALAMAT_PKP, CUSTOMER.NAMA_PKP, BON_PESANAN.NO_DO AS NO_DO_BON,LINK_CORPORATION_CUSTOMER.KODE_CORPORATION, DO.PRINT_PKP, S.NAMA_USER SALESMAN FROM DETAIL_CUSTOMER_CABANG RIGHT OUTER JOIN BON_PESANAN INNER JOIN DETAIL_BON_PESANAN ON BON_PESANAN.ID_TRANSAKSI = DETAIL_BON_PESANAN.ID_TRANSAKSI LEFT OUTER JOIN USERS ON BON_PESANAN.CRUSER = USERS.ID_USER ON DETAIL_CUSTOMER_CABANG.ID = BON_PESANAN.KODE_CUSTOMER AND DETAIL_CUSTOMER_CABANG.KODE_CABANG = BON_PESANAN.CABANG LEFT OUTER JOIN CUSTOMER ON BON_PESANAN.KODE_CUSTOMER = CUSTOMER.ID LEFT JOIN LINK_CORPORATION_CUSTOMER ON LINK_CORPORATION_CUSTOMER.ID_CUSTOMER=CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_BON_PESANAN.ID_BARANG = BARANG.ID LEFT OUTER JOIN LINK_SBU_DIVISI LEFT OUTER JOIN SBU ON LINK_SBU_DIVISI.KODE_SBU = SBU.KODE ON BON_PESANAN.DIVISI = LINK_SBU_DIVISI.KODE_DIVISI LEFT JOIN DELIVERY_ORDER DO ON BON_PESANAN.ID_DO=DO.ID_TRANSAKSI LEFT JOIN USERS S ON DO.SALES=S.ID_USER WHERE BON_PESANAN.ID_TRANSAKSI='" & NoTransaksi & "'")
                '    PrimaryReport.LabelTitle.Text = "BON PESANAN (TITIPAN)"

                'Case KeyReport.Surat_Jalan
                '    Report = New XRSJ
                '    Report.DataSource = SelectCon.execute("SELECT SURAT_JALAN.ID_TRANSAKSI, SURAT_JALAN.NO_SJ, SURAT_JALAN.TGL, SURAT_JALAN.TGL_PENGAKUAN, SURAT_JALAN.NO_NOTA, SURAT_JALAN.ID_NOTA, SURAT_JALAN.TGL_NOTA, SURAT_JALAN.DIVISI, SURAT_JALAN.KODE_CUSTOMER, SURAT_JALAN.KODE_APPROVE, SURAT_JALAN.ALAMAT_KIRIM, SURAT_JALAN.KETERANGAN_CETAK, DETAIL_SURAT_JALAN.ID_BARANG, BARANG.KODE_PABRIK, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, IIF(SURAT_JALAN.PRINT_PKP=1, CUSTOMER.NAMA_PKP, CUSTOMER.NAMA) AS NAMA_CUSTOMER, IIF(SURAT_JALAN.PRINT_PKP=1, CUSTOMER.ALAMAT_PKP, CUSTOMER.ALAMAT_KANTOR) ALAMAT_KANTOR, CUSTOMER.KOTA, DETAIL_SURAT_JALAN.QUANTITY, DETAIL_SURAT_JALAN.SATUAN, DETAIL_SURAT_JALAN.URUTAN, NOTA.ID_DO, NOTA.NO_DO, NOTA.TGL_DO, DETAIL_SURAT_JALAN.KOLI, NOTA.PENGEMUDI, NOTA.KEPALA_GUDANG, NOTA.CONTROLLER FROM NOTA RIGHT OUTER JOIN SURAT_JALAN INNER JOIN DETAIL_SURAT_JALAN ON SURAT_JALAN.ID_TRANSAKSI = DETAIL_SURAT_JALAN.ID_TRANSAKSI ON NOTA.ID_TRANSAKSI = SURAT_JALAN.ID_NOTA LEFT OUTER JOIN CUSTOMER ON SURAT_JALAN.KODE_CUSTOMER = CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_SURAT_JALAN.ID_BARANG = BARANG.ID WHERE DETAIL_SURAT_JALAN.PCS>0 AND SURAT_JALAN.ID_TRANSAKSI='" & NoTransaksi & "'")

                'Case KeyReport.Surat_Jalan_Super
                '    Report = New XRSJ
                '    Report.DataSource = SelectCon.execute("SELECT NOTA.ID_TRANSAKSI, NOTA.NO_NOTA, NOTA.TGL, NOTA.TGL_PENGAKUAN, NOTA.NO_NOTA, NOTA.ID_TRANSAKSI, NOTA.TGL_PENGAKUAN, NOTA.DIVISI, NOTA.KODE_CUSTOMER, NOTA.KODE_APPROVE, NOTA.ALAMAT_KIRIM, NOTA.KETERANGAN_CETAK, DETAIL_NOTA.ID_BARANG, BARANG.KODE_PABRIK, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.KOTA, DETAIL_NOTA.QUANTITY, DETAIL_NOTA.SATUAN, DETAIL_NOTA.URUTAN, NOTA.ID_DO, NOTA.NO_DO, NOTA.TGL_DO, DETAIL_NOTA.KOLI, NOTA.PENGEMUDI, NOTA.KEPALA_GUDANG, NOTA.CONTROLLER,NOTA.NO_SJPB AS [NO_SJ] FROM NOTA INNER JOIN DETAIL_NOTA ON NOTA.ID_TRANSAKSI = DETAIL_NOTA.ID_TRANSAKSI LEFT OUTER JOIN CUSTOMER ON NOTA.KODE_CUSTOMER = CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_NOTA.ID_BARANG = BARANG.ID WHERE NOTA.ID_TRANSAKSI='" & NoTransaksi & "'")

                '    'Case KeyReport.Nota_BON_Pesanan
                '    '    Report = New XRNotaBonPesanan
                '    '    Report.DataSource = SelectCon.execute("SELECT DELIVERY_ORDER.ID_TRANSAKSI, DELIVERY_ORDER.NO_DO, DELIVERY_ORDER.TGL, DELIVERY_ORDER.TGL_PRICE, CUSTOMER.NAMA AS NAMA_CUSTOMER, " & _
                '    '                                            "CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.KELURAHAN, CUSTOMER.KECAMATAN, CUSTOMER.NO_TELP, CUSTOMER.NO_FAX, CUSTOMER.CONTACT_PERSON, DETAIL_DELIVERY_ORDER.ID_BARANG, BARANG.NAMA AS NAMA_BARANG, " & _
                '    '                                            "DETAIL_DELIVERY_ORDER.KOLI, DETAIL_DELIVERY_ORDER.QUANTITY, DETAIL_DELIVERY_ORDER.SATUAN, DETAIL_DELIVERY_ORDER.HARGA,DETAIL_DELIVERY_ORDER.DISC, DETAIL_DELIVERY_ORDER.DISKON_SATUAN, DETAIL_DELIVERY_ORDER.URUTAN, DELIVERY_ORDER.ALAMAT_KIRIM, " & _
                '    '                                            "DELIVERY_ORDER.KETERANGAN_CETAK FROM DELIVERY_ORDER INNER JOIN DETAIL_DELIVERY_ORDER ON DELIVERY_ORDER.ID_TRANSAKSI = DETAIL_DELIVERY_ORDER.ID_TRANSAKSI AND DELIVERY_ORDER.NO_DO = DETAIL_DELIVERY_ORDER.NO_DO INNER JOIN CUSTOMER ON DELIVERY_ORDER.KODE_CUSTOMER = CUSTOMER.ID AND DELIVERY_ORDER.KODE_APPROVE = CUSTOMER.KODE_APPROVE INNER JOIN " & _
                '    '                                            "BARANG ON DETAIL_DELIVERY_ORDER.ID_BARANG = BARANG.ID WHERE DELIVERY_ORDER.ID_TRANSAKSI='" & NoTransaksi & "' ORDER BY DETAIL_DELIVERY_ORDER.URUTAN")

                'Case KeyReport.Stuffing
                '    Dim PrimaryReport As New XRNotaStuffing
                '    PrimaryReport.DataSource = SelectCon.execute("SELECT STUFFING.ID_TRANSAKSI, STUFFING.NO_DO, STUFFING.TGL, STUFFING.TGL_PENGAKUAN, STUFFING.DIVISI, STUFFING.KODE_CUSTOMER, STUFFING.KODE_APPROVE, STUFFING.ALAMAT_KIRIM, STUFFING.KETERANGAN_CETAK, DETAIL_STUFFING.ID_BARANG, DETAIL_STUFFING.KOLI, DETAIL_STUFFING.QUANTITY, DETAIL_STUFFING.SATUAN, DETAIL_STUFFING.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, SBU.NAMA AS NAMA_SBU, CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, CUSTOMER.NO_NPWP, DETAIL_STUFFING.KONVERSI, DETAIL_STUFFING.PCS, DETAIL_STUFFING.ISI, STUFFING.CABANG, STUFFING.KETERANGAN_INTERNAL, STUFFING.PERIODE, DETAIL_CUSTOMER_CABANG.NAMA_CABANG, STUFFING.NO_STUFFING, STUFFING.ID_DO, STUFFING.TGL_DO, STUFFING.GUDANG FROM CUSTOMER RIGHT OUTER JOIN STUFFING INNER JOIN DETAIL_STUFFING ON STUFFING.ID_TRANSAKSI = DETAIL_STUFFING.ID_TRANSAKSI LEFT OUTER JOIN DETAIL_CUSTOMER_CABANG ON STUFFING.KODE_CUSTOMER = DETAIL_CUSTOMER_CABANG.ID AND STUFFING.CABANG = DETAIL_CUSTOMER_CABANG.KODE_CABANG ON CUSTOMER.ID = STUFFING.KODE_CUSTOMER LEFT OUTER JOIN BARANG ON DETAIL_STUFFING.ID_BARANG = BARANG.ID LEFT OUTER JOIN LINK_SBU_DIVISI LEFT OUTER JOIN SBU ON LINK_SBU_DIVISI.KODE_SBU = SBU.KODE ON STUFFING.DIVISI = LINK_SBU_DIVISI.KODE_DIVISI WHERE STUFFING.ID_TRANSAKSI='" & NoTransaksi & "'  ORDER BY STUFFING.ID_TRANSAKSI ")
                '    Report = PrimaryReport

                'Case KeyReport.TTB
                '    Report = New XRTTB
                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE "
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "TTB.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '    Else
                '        filter = "WHERE TTB.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT TTB.ID_TRANSAKSI, TTB.NO_TTB, TTB.TGL, TTB.TGL_PENGAKUAN, TTB.NO_NOTA, TTB.TGL_NOTA, TTB.DIVISI, TTB.KODE_CUSTOMER, TTB.KODE_APPROVE, TTB.ALAMAT, TTB.GUDANG, TTB.KETERANGAN_CETAK, TTB.KETERANGAN_INTERNAL, DETAIL_TTB.ID_BARANG, DETAIL_TTB.ISI, DETAIL_TTB.KOLI, DETAIL_TTB.QUANTITY, DETAIL_TTB.SATUAN, DETAIL_TTB.KONVERSI, DETAIL_TTB.PCS, DETAIL_TTB.KETERANGAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA, IIF(PRINT_PKP=1, CUSTOMER.NAMA_PKP, CUSTOMER.NAMA) AS NAMA_CUSTOMER, IIF(PRINT_PKP=1, CUSTOMER.ALAMAT_PKP, CUSTOMER.ALAMAT_KANTOR) AS ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, DIVISI.NAMA AS NAMA_DIVISI, U.NAMA_USER FROM DIVISI RIGHT OUTER JOIN TTB INNER JOIN DETAIL_TTB ON TTB.ID_TRANSAKSI = DETAIL_TTB.ID_TRANSAKSI ON DIVISI.KODE = TTB.DIVISI LEFT OUTER JOIN CUSTOMER ON TTB.KODE_CUSTOMER = CUSTOMER.ID LEFT OUTER JOIN BARANG ON DETAIL_TTB.ID_BARANG = BARANG.ID LEFT JOIN USERS U ON TTB.CRUSER=U.ID_USER " & filter)

                'Case KeyReport.Retur_Pembelian
                '    Report = New XRReturPembelian

                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE ("
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "RETUR_PEMBELIAN.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '        filter = filter & ")"
                '    Else
                '        filter = "WHERE RETUR_PEMBELIAN.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT RETUR_PEMBELIAN.ID_TRANSAKSI, RETUR_PEMBELIAN.NO_RETUR, RETUR_PEMBELIAN.TGL, RETUR_PEMBELIAN.TGL_PENGAKUAN, RETUR_PEMBELIAN.DIVISI, RETUR_PEMBELIAN.JENIS_PPN, RETUR_PEMBELIAN.GUDANG, RETUR_PEMBELIAN.KETERANGAN_CETAK, RETUR_PEMBELIAN.KETERANGAN_INTERNAL, RETUR_PEMBELIAN.SUBTOTAL, RETUR_PEMBELIAN.DISC_QTY, RETUR_PEMBELIAN.DISC_QTY_NOMINAL, RETUR_PEMBELIAN.DISC_REG, RETUR_PEMBELIAN.DISC_REG_NOMINAL, RETUR_PEMBELIAN.DISC_1, RETUR_PEMBELIAN.DISC_1_NOMINAL, RETUR_PEMBELIAN.DISC_2, RETUR_PEMBELIAN.DISC_2_NOMINAL, RETUR_PEMBELIAN.DISC_3, RETUR_PEMBELIAN.DISC_3_NOMINAL, RETUR_PEMBELIAN.CASH_DISC, RETUR_PEMBELIAN.CASH_DISC_NOMINAL, RETUR_PEMBELIAN.DISC_QTY1, RETUR_PEMBELIAN.DISC_QTY_NOMINAL1, RETUR_PEMBELIAN.DPP, RETUR_PEMBELIAN.PPN, DETAIL_RETUR_PEMBELIAN.ID_BARANG, DETAIL_RETUR_PEMBELIAN.ISI, DETAIL_RETUR_PEMBELIAN.KOLI, DETAIL_RETUR_PEMBELIAN.QUANTITY, DETAIL_RETUR_PEMBELIAN.SATUAN, DETAIL_RETUR_PEMBELIAN.KONVERSI, DETAIL_RETUR_PEMBELIAN.PCS, DETAIL_RETUR_PEMBELIAN.HARGA, DETAIL_RETUR_PEMBELIAN.DISC, DETAIL_RETUR_PEMBELIAN.DISKON_SATUAN, DETAIL_RETUR_PEMBELIAN.URUTAN, BARANG.KODE, 'PT. MASPION' AS NAMA, 'PECINDILAN PLAZA SURABAYA' AS ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, DIVISI.NAMA AS NAMA_DIVISI, DETAIL_RETUR_PEMBELIAN.NO_TTB, DETAIL_RETUR_PEMBELIAN.KODE_PACKING FROM BARANG RIGHT OUTER JOIN RETUR_PEMBELIAN INNER JOIN DETAIL_RETUR_PEMBELIAN ON RETUR_PEMBELIAN.ID_TRANSAKSI = DETAIL_RETUR_PEMBELIAN.ID_TRANSAKSI LEFT OUTER JOIN DIVISI ON RETUR_PEMBELIAN.DIVISI = DIVISI.KODE ON BARANG.ID = DETAIL_RETUR_PEMBELIAN.ID_BARANG CROSS JOIN PERUSAHAAN INNER JOIN CUSTOMER ON PERUSAHAAN.CUST_PEMBELIAN = CUSTOMER.ID " & filter & " AND DETAIL_RETUR_PEMBELIAN.PCS>0")

                'Case KeyReport.Retur_Pembelian_Tanpa_TTB
                '    Report = New XRReturPembelianTanpaTTB

                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE ("
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "RETUR_PEMBELIAN.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '        filter = filter & ")"
                '    Else
                '        filter = "WHERE RETUR_PEMBELIAN.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT RETUR_PEMBELIAN.ID_TRANSAKSI, RETUR_PEMBELIAN.NO_RETUR, RETUR_PEMBELIAN.TGL, RETUR_PEMBELIAN.TGL_PENGAKUAN, RETUR_PEMBELIAN.DIVISI, RETUR_PEMBELIAN.JENIS_PPN, RETUR_PEMBELIAN.GUDANG, RETUR_PEMBELIAN.KETERANGAN_CETAK, RETUR_PEMBELIAN.KETERANGAN_INTERNAL, RETUR_PEMBELIAN.SUBTOTAL, RETUR_PEMBELIAN.DISC_QTY, RETUR_PEMBELIAN.DISC_QTY_NOMINAL, RETUR_PEMBELIAN.DISC_REG, RETUR_PEMBELIAN.DISC_REG_NOMINAL, RETUR_PEMBELIAN.DISC_1, RETUR_PEMBELIAN.DISC_1_NOMINAL, RETUR_PEMBELIAN.DISC_2, RETUR_PEMBELIAN.DISC_2_NOMINAL, RETUR_PEMBELIAN.DISC_3, RETUR_PEMBELIAN.DISC_3_NOMINAL, RETUR_PEMBELIAN.CASH_DISC, RETUR_PEMBELIAN.CASH_DISC_NOMINAL, RETUR_PEMBELIAN.DISC_QTY1, RETUR_PEMBELIAN.DISC_QTY_NOMINAL1, RETUR_PEMBELIAN.DPP, RETUR_PEMBELIAN.PPN, DETAIL_RETUR_PEMBELIAN.ID_BARANG, DETAIL_RETUR_PEMBELIAN.ISI, DETAIL_RETUR_PEMBELIAN.KOLI, DETAIL_RETUR_PEMBELIAN.QUANTITY, DETAIL_RETUR_PEMBELIAN.SATUAN, DETAIL_RETUR_PEMBELIAN.KONVERSI, DETAIL_RETUR_PEMBELIAN.PCS, DETAIL_RETUR_PEMBELIAN.HARGA, DETAIL_RETUR_PEMBELIAN.DISC, DETAIL_RETUR_PEMBELIAN.DISKON_SATUAN, DETAIL_RETUR_PEMBELIAN.URUTAN, BARANG.KODE, 'PT. MASPION' AS NAMA, 'PECINDILAN PLAZA SURABAYA' AS ALAMAT_KANTOR, CUSTOMER.PROPINSI, CUSTOMER.KOTA, CUSTOMER.KODE_POS, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, DIVISI.NAMA AS NAMA_DIVISI, DETAIL_RETUR_PEMBELIAN.NO_TTB, DETAIL_RETUR_PEMBELIAN.KODE_PACKING FROM BARANG RIGHT OUTER JOIN RETUR_PEMBELIAN INNER JOIN DETAIL_RETUR_PEMBELIAN ON RETUR_PEMBELIAN.ID_TRANSAKSI = DETAIL_RETUR_PEMBELIAN.ID_TRANSAKSI LEFT OUTER JOIN DIVISI ON RETUR_PEMBELIAN.DIVISI = DIVISI.KODE ON BARANG.ID = DETAIL_RETUR_PEMBELIAN.ID_BARANG CROSS JOIN PERUSAHAAN INNER JOIN CUSTOMER ON PERUSAHAAN.CUST_PEMBELIAN = CUSTOMER.ID " & filter & " AND DETAIL_RETUR_PEMBELIAN.PCS>0")

                'Case KeyReport.Retur_Penjualan
                '    Dim MyReport = New XRReturPenjualan
                '    MyReport.LblTitle.Text = "RETUR PENJUALAN"
                '    Report = MyReport

                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE "
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "RETUR_PENJUALAN.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '    Else
                '        filter = "WHERE RETUR_PENJUALAN.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT dbo.RETUR_PENJUALAN.ID_TRANSAKSI, dbo.RETUR_PENJUALAN.NO_NOTA_RETUR AS NO_RETUR, dbo.RETUR_PENJUALAN.TGL, dbo.RETUR_PENJUALAN.TGL_PENGAKUAN, dbo.RETUR_PENJUALAN.NO_TTB, dbo.RETUR_PENJUALAN.DIVISI, dbo.RETUR_PENJUALAN.JENIS_PPN, dbo.RETUR_PENJUALAN.GUDANG, dbo.RETUR_PENJUALAN.KETERANGAN_CETAK, dbo.RETUR_PENJUALAN.KETERANGAN_INTERNAL, dbo.RETUR_PENJUALAN.SUBTOTAL, dbo.RETUR_PENJUALAN.DISC_QTY, dbo.RETUR_PENJUALAN.DISC_QTY_NOMINAL, dbo.RETUR_PENJUALAN.DISC_REG, dbo.RETUR_PENJUALAN.DISC_REG_NOMINAL, dbo.RETUR_PENJUALAN.DISC_1, dbo.RETUR_PENJUALAN.DISC_1_NOMINAL, dbo.RETUR_PENJUALAN.DISC_2, dbo.RETUR_PENJUALAN.DISC_2_NOMINAL, dbo.RETUR_PENJUALAN.DISC_3, dbo.RETUR_PENJUALAN.DISC_3_NOMINAL, dbo.RETUR_PENJUALAN.CASH_DISC, dbo.RETUR_PENJUALAN.CASH_DISC_NOMINAL, dbo.RETUR_PENJUALAN.DISC_QTY1, dbo.RETUR_PENJUALAN.DISC_QTY_NOMINAL1, dbo.RETUR_PENJUALAN.DPP, dbo.RETUR_PENJUALAN.PPN, dbo.DETAIL_RETUR_PENJUALAN.ID_BARANG, dbo.DETAIL_RETUR_PENJUALAN.ISI, dbo.DETAIL_RETUR_PENJUALAN.KOLI, dbo.DETAIL_RETUR_PENJUALAN.QUANTITY, dbo.DETAIL_RETUR_PENJUALAN.SATUAN, dbo.DETAIL_RETUR_PENJUALAN.KONVERSI, dbo.DETAIL_RETUR_PENJUALAN.PCS, dbo.DETAIL_RETUR_PENJUALAN.HARGA, dbo.DETAIL_RETUR_PENJUALAN.DISC, dbo.DETAIL_RETUR_PENJUALAN.DISKON_SATUAN, dbo.DETAIL_RETUR_PENJUALAN.URUTAN, dbo.BARANG.KODE, IIF(PRINT_PKP=1, CUSTOMER.NAMA_PKP, CUSTOMER.NAMA) NAMA, IIF(PRINT_PKP=1, CUSTOMER.ALAMAT_PKP, CUSTOMER.ALAMAT_KANTOR) ALAMAT_KANTOR, dbo.CUSTOMER.PROPINSI, dbo.CUSTOMER.KOTA, dbo.CUSTOMER.KODE_POS, dbo.BARANG.KODE_PABRIK, dbo.BARANG.NAMA AS NAMA_BARANG, dbo.DIVISI.NAMA AS NAMA_DIVISI FROM dbo.DIVISI RIGHT OUTER JOIN dbo.RETUR_PENJUALAN INNER JOIN dbo.DETAIL_RETUR_PENJUALAN ON dbo.RETUR_PENJUALAN.ID_TRANSAKSI = dbo.DETAIL_RETUR_PENJUALAN.ID_TRANSAKSI LEFT OUTER JOIN dbo.CUSTOMER ON dbo.RETUR_PENJUALAN.KODE_CUSTOMER = dbo.CUSTOMER.ID ON dbo.DIVISI.KODE = dbo.RETUR_PENJUALAN.DIVISI LEFT OUTER JOIN dbo.BARANG ON dbo.DETAIL_RETUR_PENJUALAN.ID_BARANG = dbo.BARANG.ID " & filter & "")

                'Case KeyReport.Transfer_Barang_Retur
                '    Dim MyReport = New XRTransferBarangRetur
                '    MyReport.LabelNoTTB.Visible = True
                '    MyReport.LabelTTB.Visible = True
                '    Report = MyReport

                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE ("
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "TRANSFER_BARANG_RETUR.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '        filter = filter & ")"
                '    Else
                '        filter = "WHERE TRANSFER_BARANG_RETUR.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT dbo.TRANSFER_BARANG_RETUR.ID_TRANSAKSI, dbo.TRANSFER_BARANG_RETUR.NO_TRANSAKSI AS NO_TRANSFER, dbo.TRANSFER_BARANG_RETUR.TGL, dbo.TRANSFER_BARANG_RETUR.TGL_PENGAKUAN, dbo.TRANSFER_BARANG_RETUR.DIVISI,  0 JENIS_PPN, '' GUDANG, dbo.TRANSFER_BARANG_RETUR.KETERANGAN_CETAK, dbo.TRANSFER_BARANG_RETUR.KETERANGAN_INTERNAL, 0 SUBTOTAL, 0 DISC_QTY, 0 DISC_QTY_NOMINAL, 0 DISC_REG, 0 DISC_REG_NOMINAL, 0 DISC_1, 0 DISC_1_NOMINAL, 0 DISC_2, 0 DISC_2_NOMINAL, 0 DISC_3, 0 DISC_3_NOMINAL, 0 CASH_DISC, 0 CASH_DISC_NOMINAL, 0 DISC_QTY1, 0 DISC_QTY_NOMINAL1, 0 DPP, 0 PPN, dbo.DETAIL_TRANSFER_BARANG_RETUR.ID_BARANG, dbo.DETAIL_TRANSFER_BARANG_RETUR.ISI, dbo.DETAIL_TRANSFER_BARANG_RETUR.KOLI, dbo.DETAIL_TRANSFER_BARANG_RETUR.PCS, dbo.DETAIL_TRANSFER_BARANG_RETUR.QUANTITY, dbo.DETAIL_TRANSFER_BARANG_RETUR.SATUAN, dbo.DETAIL_TRANSFER_BARANG_RETUR.KONVERSI, dbo.DETAIL_TRANSFER_BARANG_RETUR.PCS, dbo.DETAIL_TRANSFER_BARANG_RETUR.HARGA, 0 DISC, 0 DISKON_SATUAN, dbo.DETAIL_TRANSFER_BARANG_RETUR.URUTAN, dbo.BARANG.KODE, dbo.BARANG.KODE_PABRIK, dbo.BARANG.NAMA AS NAMA_BARANG, dbo.DIVISI.NAMA AS NAMA, GSUMBER.NAMA_GUDANG, GTUJUAN.NAMA_GUDANG, TTB.NO_NOTA AS NO_TTB FROM dbo.DIVISI RIGHT OUTER JOIN dbo.TRANSFER_BARANG_RETUR INNER JOIN dbo.DETAIL_TRANSFER_BARANG_RETUR ON dbo.TRANSFER_BARANG_RETUR.ID_TRANSAKSI = dbo.DETAIL_TRANSFER_BARANG_RETUR.ID_TRANSAKSI ON dbo.DIVISI.KODE = dbo.TRANSFER_BARANG_RETUR.DIVISI LEFT OUTER JOIN dbo.BARANG ON dbo.DETAIL_TRANSFER_BARANG_RETUR.ID_BARANG = dbo.BARANG.ID LEFT JOIN GUDANG AS GTUJUAN ON GTUJUAN.KODE=TRANSFER_BARANG_RETUR.GUDANG_TUJUAN LEFT JOIN GUDANG AS GSUMBER ON GSUMBER.KODE=TRANSFER_BARANG_RETUR.GUDANG_SUMBER LEFT JOIN TTB ON DETAIL_TRANSFER_BARANG_RETUR.ID_TTB=TTB.ID_TRANSAKSI " & filter & " AND DETAIL_TRANSFER_BARANG_RETUR.PCS>0")

                'Case KeyReport.Penerimaan_Transfer_Barang_Retur
                '    Dim MyReport = New XRTransferBarangRetur
                '    MyReport.LabelNoTTB.Visible = True
                '    MyReport.LabelTTB.Visible = True
                '    MyReport.LblTitle.Text = "PENERIMAAN TRANSFER BARANG RETUR"
                '    Report = MyReport

                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE ("
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '        filter = filter & ")"
                '    Else
                '        filter = "WHERE PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    Report.DataSource = SelectCon.execute("SELECT dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TRANSAKSI, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.NO_TRANSAKSI AS NO_TRANSFER, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.TGL, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.TGL_PENGAKUAN, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.DIVISI,  0 JENIS_PPN, '' GUDANG, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.KETERANGAN_CETAK, dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.KETERANGAN_INTERNAL, 0 SUBTOTAL, 0 DISC_QTY, 0 DISC_QTY_NOMINAL, 0 DISC_REG, 0 DISC_REG_NOMINAL, 0 DISC_1, 0 DISC_1_NOMINAL, 0 DISC_2, 0 DISC_2_NOMINAL, 0 DISC_3, 0 DISC_3_NOMINAL, 0 CASH_DISC, 0 CASH_DISC_NOMINAL, 0 DISC_QTY1, 0 DISC_QTY_NOMINAL1, 0 DPP, 0 PPN, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.ID_BARANG, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.ISI, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.KOLI, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.PCS, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.QUANTITY, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.SATUAN, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.KONVERSI, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.PCS, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.HARGA, 0 DISC, 0 DISKON_SATUAN, dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.URUTAN, dbo.BARANG.KODE, dbo.BARANG.KODE_PABRIK, dbo.BARANG.NAMA AS NAMA_BARANG, dbo.DIVISI.NAMA AS NAMA, GSUMBER.NAMA_GUDANG, GTUJUAN.NAMA_GUDANG, TTB.NO_NOTA AS NO_TTB FROM dbo.DIVISI RIGHT OUTER JOIN dbo.PENERIMAAN_TRANSFER_BARANG_RETUR INNER JOIN dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR ON dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TRANSAKSI = dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TRANSAKSI ON dbo.DIVISI.KODE = dbo.PENERIMAAN_TRANSFER_BARANG_RETUR.DIVISI LEFT OUTER JOIN dbo.BARANG ON dbo.DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.ID_BARANG = dbo.BARANG.ID LEFT JOIN GUDANG AS GTUJUAN ON GTUJUAN.KODE=PENERIMAAN_TRANSFER_BARANG_RETUR.GUDANG_TUJUAN LEFT JOIN GUDANG AS GSUMBER ON GSUMBER.KODE=PENERIMAAN_TRANSFER_BARANG_RETUR.GUDANG_SUMBER LEFT JOIN TTB ON DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.ID_TTB=TTB.ID_TRANSAKSI " & filter & " AND DETAIL_PENERIMAAN_TRANSFER_BARANG_RETUR.PCS>0")

                'Case KeyReport.Nota_Claim
                '    Dim MyReport = New XRNotaClaim
                '    Report = MyReport
                '    Report.DataSource = SelectCon.execute("SELECT CUSTOMER.NAMA AS NAMA_CUSTOMER, CUSTOMER.ALAMAT_KANTOR, CUSTOMER.KOTA, DETAIL_CLAIM.ID_BARANG, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, DETAIL_CLAIM.KOLI, DETAIL_CLAIM.QUANTITY, DETAIL_CLAIM.SATUAN, DETAIL_CLAIM.HARGA, DETAIL_CLAIM.DISKON_SATUAN, DETAIL_CLAIM.DISC, CLAIM.ID_TRANSAKSI, CLAIM.NO_CLAIM, CLAIM.TGL, CLAIM.TGL_PENGAKUAN, DELIVERY_ORDER.ID_TRANSAKSI AS Expr1, DELIVERY_ORDER.NO_DO, DELIVERY_ORDER.TGL_PENGAKUAN AS TGL_DO, DELIVERY_ORDER.PEMBAYARAN, CLAIM.DIVISI, CLAIM.JENIS_PPN, CUSTOMER.ID, CUSTOMER.KODE_APPROVE, CUSTOMER.ALAMAT_KANTOR AS Expr2, CLAIM.GUDANG, CLAIM.KETERANGAN_CETAK, CLAIM.KETERANGAN_INTERNAL, CLAIM.SUBTOTAL, CLAIM.DISC_QTY, CLAIM.DISC_QTY_NOMINAL, CLAIM.DISC_REG, CLAIM.DISC_REG_NOMINAL, CLAIM.DISC_1, CLAIM.DISC_1_NOMINAL, CLAIM.DISC_2, CLAIM.DISC_2_NOMINAL, CLAIM.DISC_3, CLAIM.DISC_3_NOMINAL, CLAIM.CASH_DISC, CLAIM.CASH_DISC_NOMINAL, CLAIM.DISC_QTY1, CLAIM.DISC_QTY_NOMINAL1, CLAIM.DPP, CLAIM.PPN, CLAIM.PERIODE, CLAIM.CRUSER, CLAIM.CRTIME, CLAIM.MDUSER, CLAIM.MDTIME, CLAIM.BATAL, CLAIM.BAGIAN, CLAIM.KODE_EKSPEDISI, CLAIM.NO_TRUK, DETAIL_CLAIM.KONVERSI, DETAIL_CLAIM.PCS, DETAIL_CLAIM.URUTAN, CUSTOMER.NO_NPWP, CUSTOMER.NAMA_PKP, CUSTOMER.ALAMAT_PKP, CUSTOMER.KOTA_NPWP, CUSTOMER.KODE_POS_NPWP, PEMBELIAN.NO_NOTA_PENJUALAN, PEMBELIAN.ID_NOTA_PENJUALAN FROM PERUSAHAAN CROSS JOIN BARANG RIGHT OUTER JOIN CLAIM INNER JOIN DETAIL_CLAIM ON CLAIM.ID_TRANSAKSI = DETAIL_CLAIM.ID_TRANSAKSI LEFT OUTER JOIN PEMBELIAN ON CLAIM.ID_NOTA = PEMBELIAN.ID_TRANSAKSI LEFT OUTER JOIN NOTA ON NOTA.ID_TRANSAKSI = PEMBELIAN.ID_NOTA_PENJUALAN LEFT OUTER JOIN DELIVERY_ORDER ON DELIVERY_ORDER.ID_TRANSAKSI = NOTA.ID_DO ON BARANG.ID = DETAIL_CLAIM.ID_BARANG LEFT OUTER JOIN CUSTOMER ON PERUSAHAAN.CUST_PEMBELIAN = CUSTOMER.ID WHERE CLAIM.ID_TRANSAKSI='" & NoTransaksi & "'")

                'Case KeyReport.Surat_Transfer_Barang_Antar_Gudang
                '    Report = New XRTransferBarang
                '    Report.DataSource = SelectCon.execute("SELECT TRANSFER_GUDANG.ID_TRANSAKSI,DIVISI.NAMA, TRANSFER_GUDANG.NO_TRANSFER, TRANSFER_GUDANG.TGL, TRANSFER_GUDANG.TGL_PENGAKUAN,  TRANSFER_GUDANG.DIVISI, G_SUMBER.NAMA_GUDANG, G_TUJUAN.NAMA_GUDANG, TRANSFER_GUDANG.KETERANGAN_CETAK, DETAIL_TRANSFER_GUDANG.ID_BARANG, BARANG.KODE_PABRIK, BARANG.KODE, BARANG.NAMA AS NAMA_BARANG, DETAIL_TRANSFER_GUDANG.QUANTITY, DETAIL_TRANSFER_GUDANG.SATUAN, DETAIL_TRANSFER_GUDANG.URUTAN, DETAIL_TRANSFER_GUDANG.KOLI, DETAIL_TRANSFER_GUDANG.PCS, DETAIL_TRANSFER_GUDANG.HARGA FROM    TRANSFER_GUDANG INNER JOIN DETAIL_TRANSFER_GUDANG ON TRANSFER_GUDANG.ID_TRANSAKSI = DETAIL_TRANSFER_GUDANG.ID_TRANSAKSI LEFT JOIN GUDANG AS G_SUMBER ON TRANSFER_GUDANG.GUDANG_SUMBER = G_SUMBER.KODE LEFT JOIN GUDANG AS G_TUJUAN ON TRANSFER_GUDANG.GUDANG_TUJUAN = G_TUJUAN.KODE LEFT OUTER JOIN  BARANG ON DETAIL_TRANSFER_GUDANG.ID_BARANG = BARANG.ID LEFT JOIN DIVISI ON DIVISI.KODE=TRANSFER_GUDANG.DIVISI WHERE DETAIL_TRANSFER_GUDANG.PCS>0 AND TRANSFER_GUDANG.ID_TRANSAKSI='" & NoTransaksi & "'")

                'Case KeyReport.Stok_Awal_Barang
                '    Report = New XRSaldoStok
                '    Report.DataSource = SelectCon.execute("SELECT A.GUDANG,C.NAMA_GUDANG,B.ID_BARANG AS ID,B.PCS AS QUANTITY,0 AS DZ,SATUAN,PCS,SATUAN AS SATUAN_SUPER1,D.KODE,D.NAMA,B.HARGA,B.QUANTITY*B.HARGA AS JUMLAH_HARGA,B.QUANTITY*B.HARGA AS KARTU_STOK,0 AS BEDA_HARGA,E.NAMA AS NAMA_DIVISI FROM SALDO_AWAL_BARANG A INNER JOIN DETAIL_SALDO_AWAL_BARANG B ON A.ID_TRANSAKSI=B.ID_TRANSAKSI LEFT JOIN GUDANG C ON A.GUDANG=C.KODE LEFT JOIN BARANG D ON B.ID_BARANG=D.ID LEFT JOIN DIVISI E ON A.DIVISI=E.KODE WHERE A.ID_TRANSAKSI='" & NoTransaksi & "'")

                'Case KeyReport.Adjusment_Stok
                '    Dim PrimaryReport As New XRAdjusmentStok
                '    Dim filter As String = ""
                '    If Not IsNothing(MultiNo) Then
                '        For Each Str As String In MultiNo
                '            If Str = MultiNo(0) Then : filter = filter & " WHERE "
                '            Else : filter = filter & " OR " : End If
                '            filter = filter & "ADJUSMENT_STOK.ID_TRANSAKSI='" & Str & "'"
                '        Next
                '    Else
                '        filter = "WHERE ADJUSMENT_STOK.ID_TRANSAKSI='" & NoTransaksi & "'"
                '    End If

                '    PrimaryReport.DataSource = SelectCon.execute("SELECT DISTINCT ADJUSMENT_STOK.ID_TRANSAKSI, ADJUSMENT_STOK.NO_TRANSAKSI, ADJUSMENT_STOK.TGL, ADJUSMENT_STOK.TGL_PENGAKUAN, DIVISI.NAMA AS DIVISI, GUDANG.NAMA_GUDANG, ADJUSMENT_STOK.JENIS_PPN, ADJUSMENT_STOK.JENIS_PPN, ADJUSMENT_STOK.SIFAT JENIS, ADJUSMENT_STOK.KETERANGAN_CETAK, ADJUSMENT_STOK.SUBTOTAL, ADJUSMENT_STOK.DPP, ADJUSMENT_STOK.PPN, DETAIL_ADJUSMENT_STOK.ID_BARANG, DETAIL_ADJUSMENT_STOK.KOLI, DETAIL_ADJUSMENT_STOK.QUANTITY, DETAIL_ADJUSMENT_STOK.SATUAN, DETAIL_ADJUSMENT_STOK.HARGA, 0 DISC, 0 DISKON_SATUAN, DETAIL_ADJUSMENT_STOK.URUTAN, BARANG.KODE, BARANG.KODE_PABRIK, BARANG.NAMA AS NAMA_BARANG, DETAIL_ADJUSMENT_STOK.KONVERSI, DETAIL_ADJUSMENT_STOK.PCS, DETAIL_ADJUSMENT_STOK.ISI, ADJUSMENT_STOK.KETERANGAN_INTERNAL, ADJUSMENT_STOK.DISC_QTY, ADJUSMENT_STOK.DISC_QTY_NOMINAL, ADJUSMENT_STOK.DISC_REG, ADJUSMENT_STOK.DISC_REG_NOMINAL, ADJUSMENT_STOK.DISC_1, ADJUSMENT_STOK.DISC_1_NOMINAL, ADJUSMENT_STOK.DISC_2, ADJUSMENT_STOK.DISC_2_NOMINAL, ADJUSMENT_STOK.DISC_3, ADJUSMENT_STOK.DISC_3_NOMINAL, ADJUSMENT_STOK.CASH_DISC, ADJUSMENT_STOK.CASH_DISC_NOMINAL, ADJUSMENT_STOK.DISC_QTY1, ADJUSMENT_STOK.DISC_QTY_NOMINAL1, ADJUSMENT_STOK.PERIODE, USERS.NAMA_USER FROM BARANG RIGHT OUTER JOIN USERS RIGHT OUTER JOIN ADJUSMENT_STOK INNER JOIN DETAIL_ADJUSMENT_STOK ON ADJUSMENT_STOK.ID_TRANSAKSI = DETAIL_ADJUSMENT_STOK.ID_TRANSAKSI LEFT OUTER JOIN GUDANG ON ADJUSMENT_STOK.GUDANG = GUDANG.KODE LEFT OUTER JOIN DIVISI ON ADJUSMENT_STOK.DIVISI = DIVISI.KODE ON USERS.ID_USER = ADJUSMENT_STOK.CRUSER ON BARANG.ID = DETAIL_ADJUSMENT_STOK.ID_BARANG " & filter)
                '    Report = PrimaryReport
        End Select
        Try
            Report.DataMember = Nothing
            Report.CreateDocument()
            DocumentViewer1.DocumentSource = Report
        Catch
        End Try
    End Sub

    Private Sub BarButtonItem2_ItemClick(sender As System.Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnRibbbonDesigner.ItemClick
        Report.ShowRibbonDesignerDialog()
        Report.CreateDocument()
        DocumentViewer1.DocumentSource = Report
    End Sub

    Private Sub BtnStandardDesigner_ItemClick(sender As System.Object, e As DevExpress.XtraBars.ItemClickEventArgs) Handles BtnStandardDesigner.ItemClick
        Report.ShowDesignerDialog()
        Report.CreateDocument()
        DocumentViewer1.DocumentSource = Report
    End Sub
End Class